/**
 * ActiveSupport::TimeZone::MAPPING — maps friendly names to IANA timezone IDs.
 * Source: Rails ActiveSupport (https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html)
 */
const activeSupportToIana: Record<string, string> = {
  "International Date Line West": "Etc/GMT+12",
  "American Samoa": "Pacific/Pago_Pago",
  "Midway Island": "Pacific/Midway",
  "Hawaii": "Pacific/Honolulu",
  "Alaska": "America/Juneau",
  "Pacific Time (US & Canada)": "America/Los_Angeles",
  "Tijuana": "America/Tijuana",
  "Arizona": "America/Phoenix",
  "Mazatlan": "America/Mazatlan",
  "Mountain Time (US & Canada)": "America/Denver",
  "Central America": "America/Guatemala",
  "Central Time (US & Canada)": "America/Chicago",
  "Chihuahua": "America/Chihuahua",
  "Guadalajara": "America/Mexico_City",
  "Mexico City": "America/Mexico_City",
  "Monterrey": "America/Monterrey",
  "Saskatchewan": "America/Regina",
  "Bogota": "America/Bogota",
  "Eastern Time (US & Canada)": "America/New_York",
  "Indiana (East)": "America/Indiana/Indianapolis",
  "Lima": "America/Lima",
  "Quito": "America/Lima",
  "Asuncion": "America/Asuncion",
  "Atlantic Time (Canada)": "America/Halifax",
  "Caracas": "America/Caracas",
  "Georgetown": "America/Guyana",
  "La Paz": "America/La_Paz",
  "Puerto Rico": "America/Puerto_Rico",
  "Santiago": "America/Santiago",
  "Newfoundland": "America/St_Johns",
  "Brasilia": "America/Sao_Paulo",
  "Buenos Aires": "America/Argentina/Buenos_Aires",
  "Montevideo": "America/Montevideo",
  "Greenland": "America/Godthab",
  "Mid-Atlantic": "Atlantic/South_Georgia",
  "Azores": "Atlantic/Azores",
  "Cape Verde Is.": "Atlantic/Cape_Verde",
  "Edinburgh": "Europe/London",
  "Lisbon": "Europe/Lisbon",
  "London": "Europe/London",
  "Monrovia": "Africa/Monrovia",
  "UTC": "Etc/UTC",
  "Amsterdam": "Europe/Amsterdam",
  "Belgrade": "Europe/Belgrade",
  "Berlin": "Europe/Berlin",
  "Bern": "Europe/Zurich",
  "Bratislava": "Europe/Bratislava",
  "Brussels": "Europe/Brussels",
  "Budapest": "Europe/Budapest",
  "Casablanca": "Africa/Casablanca",
  "Copenhagen": "Europe/Copenhagen",
  "Dublin": "Europe/Dublin",
  "Ljubljana": "Europe/Ljubljana",
  "Madrid": "Europe/Madrid",
  "Paris": "Europe/Paris",
  "Prague": "Europe/Prague",
  "Rome": "Europe/Rome",
  "Sarajevo": "Europe/Sarajevo",
  "Skopje": "Europe/Skopje",
  "Stockholm": "Europe/Stockholm",
  "Vienna": "Europe/Vienna",
  "Warsaw": "Europe/Warsaw",
  "West Central Africa": "Africa/Algiers",
  "Zagreb": "Europe/Zagreb",
  "Zurich": "Europe/Zurich",
  "Athens": "Europe/Athens",
  "Bucharest": "Europe/Bucharest",
  "Cairo": "Africa/Cairo",
  "Harare": "Africa/Harare",
  "Helsinki": "Europe/Helsinki",
  "Jerusalem": "Asia/Jerusalem",
  "Kaliningrad": "Europe/Kaliningrad",
  "Kyiv": "Europe/Kyiv",
  "Pretoria": "Africa/Johannesburg",
  "Riga": "Europe/Riga",
  "Sofia": "Europe/Sofia",
  "Tallinn": "Europe/Tallinn",
  "Vilnius": "Europe/Vilnius",
  "Baghdad": "Asia/Baghdad",
  "Istanbul": "Europe/Istanbul",
  "Kuwait": "Asia/Kuwait",
  "Minsk": "Europe/Minsk",
  "Moscow": "Europe/Moscow",
  "Nairobi": "Africa/Nairobi",
  "Riyadh": "Asia/Riyadh",
  "St. Petersburg": "Europe/Moscow",
  "Volgograd": "Europe/Volgograd",
  "Tehran": "Asia/Tehran",
  "Abu Dhabi": "Asia/Muscat",
  "Baku": "Asia/Baku",
  "Muscat": "Asia/Muscat",
  "Samara": "Europe/Samara",
  "Tbilisi": "Asia/Tbilisi",
  "Yerevan": "Asia/Yerevan",
  "Kabul": "Asia/Kabul",
  "Ekaterinburg": "Asia/Yekaterinburg",
  "Islamabad": "Asia/Karachi",
  "Karachi": "Asia/Karachi",
  "Tashkent": "Asia/Tashkent",
  "Chennai": "Asia/Kolkata",
  "Kolkata": "Asia/Kolkata",
  "Mumbai": "Asia/Kolkata",
  "New Delhi": "Asia/Kolkata",
  "Sri Jayawardenepura": "Asia/Colombo",
  "Kathmandu": "Asia/Kathmandu",
  "Almaty": "Asia/Almaty",
  "Astana": "Asia/Dhaka",
  "Dhaka": "Asia/Dhaka",
  "Urumqi": "Asia/Urumqi",
  "Rangoon": "Asia/Rangoon",
  "Bangkok": "Asia/Bangkok",
  "Hanoi": "Asia/Bangkok",
  "Jakarta": "Asia/Jakarta",
  "Krasnoyarsk": "Asia/Krasnoyarsk",
  "Novosibirsk": "Asia/Novosibirsk",
  "Beijing": "Asia/Shanghai",
  "Chongqing": "Asia/Chongqing",
  "Hong Kong": "Asia/Hong_Kong",
  "Irkutsk": "Asia/Irkutsk",
  "Kuala Lumpur": "Asia/Kuala_Lumpur",
  "Perth": "Australia/Perth",
  "Singapore": "Asia/Singapore",
  "Taipei": "Asia/Taipei",
  "Ulaanbaatar": "Asia/Ulaanbaatar",
  "Osaka": "Asia/Tokyo",
  "Sapporo": "Asia/Tokyo",
  "Seoul": "Asia/Seoul",
  "Tokyo": "Asia/Tokyo",
  "Yakutsk": "Asia/Yakutsk",
  "Adelaide": "Australia/Adelaide",
  "Darwin": "Australia/Darwin",
  "Brisbane": "Australia/Brisbane",
  "Canberra": "Australia/Melbourne",
  "Guam": "Pacific/Guam",
  "Hobart": "Australia/Hobart",
  "Melbourne": "Australia/Melbourne",
  "Port Moresby": "Pacific/Port_Moresby",
  "Sydney": "Australia/Sydney",
  "Vladivostok": "Asia/Vladivostok",
  "Magadan": "Asia/Magadan",
  "New Caledonia": "Pacific/Noumea",
  "Solomon Is.": "Pacific/Guadalcanal",
  "Srednekolymsk": "Asia/Srednekolymsk",
  "Auckland": "Pacific/Auckland",
  "Fiji": "Pacific/Fiji",
  "Kamchatka": "Asia/Kamchatka",
  "Marshall Is.": "Pacific/Majuro",
  "Wellington": "Pacific/Auckland",
  "Chatham Is.": "Pacific/Chatham",
  "Nuku'alofa": "Pacific/Tongatapu",
  "Samoa": "Pacific/Apia",
  "Tokelau Is.": "Pacific/Fakaofo",
};

// Build reverse mapping (IANA -> ActiveSupport name). For duplicates, first wins.
const ianaToActiveSupport: Record<string, string> = {};
for (const [name, iana] of Object.entries(activeSupportToIana)) {
  if (!(iana in ianaToActiveSupport)) {
    ianaToActiveSupport[iana] = name;
  }
}

/**
 * UTC offsets in minutes for each ActiveSupport timezone.
 * These are the standard (non-DST) offsets.
 */
const utcOffsets: Record<string, number> = {
  "International Date Line West": -720,
  "American Samoa": -660,
  "Midway Island": -660,
  "Hawaii": -600,
  "Alaska": -540,
  "Pacific Time (US & Canada)": -480,
  "Tijuana": -480,
  "Arizona": -420,
  "Mazatlan": -420,
  "Mountain Time (US & Canada)": -420,
  "Central America": -360,
  "Central Time (US & Canada)": -360,
  "Chihuahua": -360,
  "Guadalajara": -360,
  "Mexico City": -360,
  "Monterrey": -360,
  "Saskatchewan": -360,
  "Bogota": -300,
  "Eastern Time (US & Canada)": -300,
  "Indiana (East)": -300,
  "Lima": -300,
  "Quito": -300,
  "Asuncion": -240,
  "Atlantic Time (Canada)": -240,
  "Caracas": -240,
  "Georgetown": -240,
  "La Paz": -240,
  "Puerto Rico": -240,
  "Santiago": -240,
  "Newfoundland": -210,
  "Brasilia": -180,
  "Buenos Aires": -180,
  "Montevideo": -180,
  "Greenland": -180,
  "Mid-Atlantic": -120,
  "Azores": -60,
  "Cape Verde Is.": -60,
  "Edinburgh": 0,
  "Lisbon": 0,
  "London": 0,
  "Monrovia": 0,
  "UTC": 0,
  "Amsterdam": 60,
  "Belgrade": 60,
  "Berlin": 60,
  "Bern": 60,
  "Bratislava": 60,
  "Brussels": 60,
  "Budapest": 60,
  "Casablanca": 60,
  "Copenhagen": 60,
  "Dublin": 60,
  "Ljubljana": 60,
  "Madrid": 60,
  "Paris": 60,
  "Prague": 60,
  "Rome": 60,
  "Sarajevo": 60,
  "Skopje": 60,
  "Stockholm": 60,
  "Vienna": 60,
  "Warsaw": 60,
  "West Central Africa": 60,
  "Zagreb": 60,
  "Zurich": 60,
  "Athens": 120,
  "Bucharest": 120,
  "Cairo": 120,
  "Harare": 120,
  "Helsinki": 120,
  "Jerusalem": 120,
  "Kaliningrad": 120,
  "Kyiv": 120,
  "Pretoria": 120,
  "Riga": 120,
  "Sofia": 120,
  "Tallinn": 120,
  "Vilnius": 120,
  "Baghdad": 180,
  "Istanbul": 180,
  "Kuwait": 180,
  "Minsk": 180,
  "Moscow": 180,
  "Nairobi": 180,
  "Riyadh": 180,
  "St. Petersburg": 180,
  "Volgograd": 180,
  "Tehran": 210,
  "Abu Dhabi": 240,
  "Baku": 240,
  "Muscat": 240,
  "Samara": 240,
  "Tbilisi": 240,
  "Yerevan": 240,
  "Kabul": 270,
  "Ekaterinburg": 300,
  "Islamabad": 300,
  "Karachi": 300,
  "Tashkent": 300,
  "Chennai": 330,
  "Kolkata": 330,
  "Mumbai": 330,
  "New Delhi": 330,
  "Sri Jayawardenepura": 330,
  "Kathmandu": 345,
  "Almaty": 360,
  "Astana": 360,
  "Dhaka": 360,
  "Urumqi": 360,
  "Rangoon": 390,
  "Bangkok": 420,
  "Hanoi": 420,
  "Jakarta": 420,
  "Krasnoyarsk": 420,
  "Novosibirsk": 420,
  "Beijing": 480,
  "Chongqing": 480,
  "Hong Kong": 480,
  "Irkutsk": 480,
  "Kuala Lumpur": 480,
  "Perth": 480,
  "Singapore": 480,
  "Taipei": 480,
  "Ulaanbaatar": 480,
  "Osaka": 540,
  "Sapporo": 540,
  "Seoul": 540,
  "Tokyo": 540,
  "Yakutsk": 540,
  "Adelaide": 570,
  "Darwin": 570,
  "Brisbane": 600,
  "Canberra": 600,
  "Guam": 600,
  "Hobart": 600,
  "Melbourne": 600,
  "Port Moresby": 600,
  "Sydney": 600,
  "Vladivostok": 600,
  "Magadan": 660,
  "New Caledonia": 660,
  "Solomon Is.": 660,
  "Srednekolymsk": 660,
  "Auckland": 720,
  "Fiji": 720,
  "Kamchatka": 720,
  "Marshall Is.": 720,
  "Wellington": 720,
  "Chatham Is.": 765,
  "Nuku'alofa": 780,
  "Samoa": 780,
  "Tokelau Is.": 780,
};

export function getIanaTimezone(activeSupportName: string): string | undefined {
  return activeSupportToIana[activeSupportName];
}

export function getActiveSupportName(ianaId: string): string | undefined {
  return ianaToActiveSupport[ianaId];
}

export function resolveToActiveSupportName(timezone: string): string | undefined {
  if (timezone in activeSupportToIana) return timezone;
  return ianaToActiveSupport[timezone];
}

export function getUtcOffset(activeSupportName: string): number | undefined {
  return utcOffsets[activeSupportName];
}

export function formatOffset(minutes: number, format: 'GMT' | 'UTC' = 'GMT'): string {
  const sign = minutes >= 0 ? '+' : '-';
  const abs = Math.abs(minutes);
  const h = String(Math.floor(abs / 60)).padStart(2, '0');
  const m = String(abs % 60).padStart(2, '0');
  return `${format}${sign}${h}:${m}`;
}
